plugins {
    id 'java'
    id 'com.github.gmazzo.buildconfig' version '3.1.0'
    id 'com.christophecvb.touchportal.plugin-packager' version "+"
}

def mainClassSimpleName = 'TouchPortalSampleJavaPlugin'
def mainClassPackage = 'com.christophecvb.touchportal.samplejava'
group mainClassPackage
version versionName

tpPlugin.mainClassSimpleName = mainClassSimpleName

// Version of Java for Builds to Target - Set this here or in a task. Defaults to 8 if not set
//ext.javaVersionTarget = 8
//tpPlugin.targetJvmVersion.set(provider { ext.javaVersionTarget as Integer })

buildConfig {
    packageName = project.group

    buildConfigField 'String', 'NAME', "\"${project.name}\""
    buildConfigField 'String', 'VERSION_NAME', "\"${versionName}\""
    buildConfigField 'long', 'VERSION_CODE', versionCode + ''
}

dependencies {
    implementation project(':Library')

    annotationProcessor project(':AnnotationsProcessor')
}
