plugins {
    id 'java'
    alias(libs.plugins.buildConfig)
    id 'com.christophecvb.touchportal.plugin-packager' version "+"
}

def mainClassSimpleName = 'TouchPortalSampleJavaPlugin'
def mainClassPackage = 'com.christophecvb.touchportal.samplejava'
group mainClassPackage
version versionName

tpPlugin.mainClassSimpleName = mainClassSimpleName

// Java Version to Target with Java 8 as default. Can be changed in a task e.g. buildTargetJvmVersion.set(17)
final def buildTargetJvmVersion = objects.property(Integer.class).convention(8) as Property<Integer>

buildConfig {
    packageName = project.group

    buildConfigField 'String', 'NAME', "\"${project.name}\""
    buildConfigField 'String', 'VERSION_NAME', "\"${versionName}\""
    buildConfigField 'long', 'VERSION_CODE', versionCode + ''
}

dependencies {
    implementation project(':Library')

    annotationProcessor project(':AnnotationsProcessor')
}

// Version of Java for Builds to Target - Set this here or in a task.
if (JavaVersion.current().java9Compatible) {
    tasks.withType(JavaCompile).configureEach {
        options.release = buildTargetJvmVersion
    }
}