plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.9.25'
    id 'org.jetbrains.kotlin.kapt' version '1.9.25'
    id 'java'
    id 'com.github.gmazzo.buildconfig' version '3.0.0'
    id 'com.christophecvb.touchportal.plugin-packager' version "$versionName+"
}

def mainClassSimpleName = 'TouchPortalSampleKotlinPlugin'
def mainClassPackage = 'com.christophecvb.touchportal.samplekotlin'
group mainClassPackage
version versionName

tpPlugin.mainClassSimpleName = mainClassSimpleName

ext.javaVersionTarget = 8 // Version of Java for Builds to Target - Change this here or in a task
tpPlugin.targetJvmVersion.set(provider { ext.javaVersionTarget as Integer })

buildConfig {
    packageName = project.group

    useKotlinOutput()

    buildConfigField 'String', 'NAME', "\"${project.name}\""
    buildConfigField 'String', 'VERSION_NAME', "\"${versionName}\""
    buildConfigField 'long', 'VERSION_CODE', versionCode + ''
}

dependencies {
    implementation libs.kotlinstdlib

    implementation project(':Library')

    kapt project(':AnnotationsProcessor')
}
