[versions]

## Libs
gson = "2.11.0"
okHttp = "4.12.0"
autoService = "1.1.1"
javaPoet = "1.13.0"

junit = "4.13.2"
kotlinGradle = "2.0.21"

## Gradle Plugins
pluginPublish = "1.2.2"
buildConfig = "3.0.0"

## Kotlin Sample
kotlin = "2.0.21"



[libraries]

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
autoService = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
javaPoet = { module = "com.squareup:javapoet", version.ref = "javaPoet" }

# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-gradle-plugins-bom
kotlin-gradle-pluginsBom = { module = "org.jetbrains.kotlin:kotlin-gradle-plugins-bom", version.ref = "kotlinGradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradle" }

## Testing

# https://mvnrepository.com/artifact/org.junit/junit-bom
junit-base = { module = "junit:junit", version.ref = "junit" }


## Kotlin Sample
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-bom
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdLib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }



[plugins]

buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }

## Kotlin Sample
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }



[bundles]
junitBundle = ["junit-base"]